import "./globals.css";
import Header from "../components/myComponents/header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-[100vw]">
        {/* Fixed Header */}
        <div className="w-full fixed top-0 z-50">
          <Header />
        </div>

        <main className="pt-[80px]">{children}</main>
      </body>
    </html>
  );
}
